// SFZ generator - Convert AKP data to SFZ format

use crate::formats::{common::*, akp::AkaiProgram};
use super::types::*;
use log::debug;

impl AkaiProgram {
    /// Convert this AKP program to SFZ format string
    pub fn to_sfz_string(&self) -> String {
        let mut content = String::new();
        content.push_str("// Generated by Rusty Samplers\n");
        content.push_str("// Professional AKP to SFZ Converter\n\n");

        for keygroup in &self.keygroups {
            if let Some(region) = convert_keygroup_to_region(keygroup) {
                content.push_str(&region.to_sfz_string());
                content.push_str("\n\n");
            }
        }

        content
    }
    
    /// Convert this AKP program to a structured SFZ program
    pub fn to_sfz_program(&self) -> SfzProgram {
        let mut program = SfzProgram::new();
        
        for keygroup in &self.keygroups {
            if let Some(region) = convert_keygroup_to_region(keygroup) {
                program.add_region(region);
            }
        }
        
        debug!("Converted {} keygroups to {} SFZ regions", 
               self.keygroups.len(), program.region_count());
        
        program
    }
}

/// Convert an AKP keygroup to an SFZ region
fn convert_keygroup_to_region(keygroup: &Keygroup) -> Option<SfzRegion> {
    // Must have a sample to be valid
    let sample = keygroup.sample.as_ref()?;
    
    let mut region = SfzRegion::new(
        sample.filename.clone(),
        keygroup.zone.low_key,
        keygroup.zone.high_key,
        keygroup.zone.low_vel,
        keygroup.zone.high_vel,
    );
    
    // Convert tuning parameters
    if let Some(tune) = &keygroup.tune {
        region.volume = Some(conversion::akp_level_to_db(tune.level));
        region.tune = Some(tune.semitone);
        region.fine_tune = Some(tune.fine_tune);
    }
    
    // Convert amplitude envelope
    if let Some(env) = &keygroup.amp_env {
        region.ampeg_attack = Some(conversion::akp_envelope_to_seconds(env.attack, 1.0));
        region.ampeg_decay = Some(conversion::akp_envelope_to_seconds(env.decay, 2.0));
        region.ampeg_sustain = Some(env.sustain);
        region.ampeg_release = Some(conversion::akp_envelope_to_seconds(env.release, 4.0));
    }
    
    // Convert filter parameters
    if let Some(filter) = &keygroup.filter {
        if filter.filter_type > 0 {
            region.fil_type = Some(match filter.filter_type {
                1 => "lpf_2p".to_string(),
                2 => "bpf_2p".to_string(),
                3 => "hpf_2p".to_string(),
                _ => "lpf_2p".to_string(), // Default to low-pass
            });
            
            region.cutoff = Some(conversion::akp_cutoff_to_hz(filter.cutoff));
            region.resonance = Some(conversion::akp_resonance_to_db(filter.resonance));
        }
    }
    
    // Convert filter envelope (use filter_env if available)
    if let Some(env) = &keygroup.filter_env {
        region.fileg_attack = Some(conversion::akp_envelope_to_seconds(env.attack, 1.0));
        region.fileg_decay = Some(conversion::akp_envelope_to_seconds(env.decay, 2.0));
        region.fileg_sustain = Some(env.sustain);
        region.fileg_release = Some(conversion::akp_envelope_to_seconds(env.release, 4.0));
    }
    
    // Convert LFO parameters
    if let Some(lfo) = &keygroup.lfo1 {
        region.lfo1_freq = Some(conversion::akp_lfo_rate_to_hz(lfo.rate));
    }
    
    if let Some(lfo) = &keygroup.lfo2 {
        region.lfo2_freq = Some(conversion::akp_lfo_rate_to_hz(lfo.rate));
    }
    
    Some(region)
}

impl SfzProgram {
    /// Convert this SFZ program to a formatted string
    pub fn to_string(&self) -> String {
        let mut content = String::new();
        content.push_str("// Generated by Rusty Samplers\n");
        content.push_str("// Professional AKP to SFZ Converter\n\n");
        
        // Add global settings if present
        if let Some(global) = &self.global_settings {
            content.push_str("<global>\n");
            if let Some(volume) = global.volume {
                content.push_str(&format!("volume={:.2}\n", volume));
            }
            if let Some(tune) = global.tune {
                content.push_str(&format!("tune={}\n", tune));
            }
            content.push_str("\n");
        }
        
        // Add all regions
        for region in &self.regions {
            content.push_str(&region.to_sfz_string());
            content.push_str("\n\n");
        }
        
        content
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_keygroup_conversion() {
        let mut keygroup = Keygroup::new(60, 64, 1, 127);
        keygroup.sample = Some(Sample {
            filename: "test.wav".to_string(),
        });
        keygroup.tune = Some(Tune {
            level: 75,
            semitone: 12,
            fine_tune: -5,
        });
        
        let region = convert_keygroup_to_region(&keygroup).unwrap();
        
        assert_eq!(region.sample, "test.wav");
        assert_eq!(region.lokey, 60);
        assert_eq!(region.hikey, 64);
        assert_eq!(region.tune, Some(12));
        assert_eq!(region.fine_tune, Some(-5));
        assert!(region.volume.is_some());
    }
    
    #[test]
    fn test_filter_conversion() {
        let mut keygroup = Keygroup::new(60, 64, 1, 127);
        keygroup.sample = Some(Sample {
            filename: "test.wav".to_string(),
        });
        keygroup.filter = Some(Filter {
            cutoff: 50,
            resonance: 25,
            filter_type: 1, // Low-pass
        });
        
        let region = convert_keygroup_to_region(&keygroup).unwrap();
        
        assert_eq!(region.fil_type, Some("lpf_2p".to_string()));
        assert!(region.cutoff.is_some());
        assert!(region.resonance.is_some());
    }
    
    #[test]
    fn test_invalid_keygroup_without_sample() {
        let keygroup = Keygroup::new(60, 64, 1, 127);
        // No sample assigned
        
        let region = convert_keygroup_to_region(&keygroup);
        assert!(region.is_none());
    }
}