use crate::types::{AkaiProgram, EnvelopeTiming, Keygroup, mod_source_name, mod_source_sfz_suffix, mod_source_type};

impl AkaiProgram {
    pub fn to_sfz_string(&self) -> String {
        let mut sfz = String::new();
        sfz.push_str("// Generated by Rusty Samplers\n\n");

        // Global header — program-level settings that apply to all regions
        let has_global = self.tuning.is_some() || self.output.is_some()
            || self.lfo1.is_some() || self.lfo2.is_some();
        if has_global {
            sfz.push_str("<global>\n");

            if let Some(tuning) = &self.tuning {
                sfz.push_str(&format!("bend_up={}\n", tuning.pitchbend_up as i32 * 100));
                sfz.push_str(&format!("bend_down=-{}\n", tuning.pitchbend_down as i32 * 100));

                // Aftertouch → pitch (hardwired)
                if tuning.aftertouch != 0 {
                    sfz.push_str(&format!("pitch_chanaft={}\n", tuning.aftertouch as i32 * 100));
                }
            }

            if let Some(output) = &self.output {
                if output.loudness != 85 {
                    sfz.push_str(&format!("amplitude={}\n", output.loudness));
                }

                // AKP range (-100..100) maps directly to SFZ amp_veltrack (-100..100)
                let vel_track = output.velocity_sensitivity as i32;
                if vel_track != 100 {
                    sfz.push_str(&format!("amp_veltrack={vel_track}\n"));
                }
            }

            // LFO hardwired modwheel/aftertouch shortcuts (global scope)
            if let Some(lfo) = &self.lfo1 {
                if lfo.modwheel > 0 {
                    let depth_cents = lfo.modwheel as f32;
                    sfz.push_str(&format!("pitchlfo_depthcc1={depth_cents:.0}\n"));
                }
                if lfo.aftertouch > 0 {
                    let depth_cents = lfo.aftertouch as f32;
                    sfz.push_str(&format!("pitchlfo_depthchanaft={depth_cents:.0}\n"));
                }
            }

            sfz.push('\n');
        }

        for keygroup in &self.keygroups {
            // Each zone becomes a <region>
            let zones: Vec<_> = if keygroup.zones.is_empty() {
                // No zones — emit one region with no sample (keeps envelope/filter data visible)
                vec![None]
            } else {
                keygroup.zones.iter().map(Some).collect()
            };

            for zone in &zones {
                sfz.push_str("<region>\n");

                // Sample + velocity from zone
                if let Some(z) = zone {
                    sfz.push_str(&format!("sample={}\n", z.sample_name));
                    sfz.push_str(&format!("lokey={}\nhikey={}\n", keygroup.low_key, keygroup.high_key));
                    sfz.push_str(&format!("lovel={}\nhivel={}\n", z.low_vel, z.high_vel));

                    // Zone-level tuning (additive with keygroup)
                    let semitone = keygroup.semitone_tune as i16 + z.semitone_tune as i16;
                    let fine = keygroup.fine_tune as i16 + z.fine_tune as i16;
                    if semitone != 0 {
                        sfz.push_str(&format!("transpose={semitone}\n"));
                    }
                    if fine != 0 {
                        sfz.push_str(&format!("tune={fine}\n"));
                    }

                    // Zone pan
                    if z.pan != 0 {
                        sfz.push_str(&format!("pan={}\n", z.pan));
                    }

                    // Zone level
                    if z.level != 0 {
                        sfz.push_str(&format!("volume={}\n", z.level));
                    }

                    // Playback mode from zone
                    match z.playback {
                        0 => sfz.push_str("loop_mode=no_loop\n"),
                        1 => sfz.push_str("loop_mode=one_shot\n"),
                        2 => sfz.push_str("loop_mode=loop_continuous\n"),
                        3 => sfz.push_str("loop_mode=loop_sustain\n"),
                        _ => {} // 4=AS SAMPLE, use sample header default
                    }
                } else {
                    sfz.push_str(&format!("lokey={}\nhikey={}\n", keygroup.low_key, keygroup.high_key));
                }

                // Amp envelope
                if let Some(env) = &keygroup.amp_env {
                    sfz.push_str(&format!("ampeg_attack={:.3}\n", env.attack_time()));
                    sfz.push_str(&format!("ampeg_decay={:.3}\n", env.decay_time()));
                    sfz.push_str(&format!("ampeg_sustain={}\n", env.sustain));
                    sfz.push_str(&format!("ampeg_release={:.3}\n", env.release_time()));

                    if env.velocity_attack != 0 {
                        sfz.push_str(&format!("ampeg_vel2attack={}\n", env.velocity_attack));
                    }
                    if env.on_vel_release != 0 {
                        sfz.push_str(&format!("ampeg_vel2release={}\n", env.on_vel_release));
                    }
                    if env.keyscale != 0 {
                        sfz.push_str(&format!("// AKP amp env keyscale={}\n", env.keyscale));
                    }
                }

                // Filter
                if let Some(filter) = &keygroup.filter {
                    sfz.push_str(&format!("fil_type={}\n", filter.sfz_filter_type()));
                    sfz.push_str(&format!("cutoff={:.1}\n", filter.cutoff_hz()));
                    sfz.push_str(&format!("resonance={:.1}\n", filter.resonance_db()));

                    if filter.keyboard_track != 0 {
                        // Convert -36..+36 semitones to cents
                        sfz.push_str(&format!("fil_keytrack={}\n", filter.keyboard_track as i32 * 100));
                    }
                }

                // Filter envelope
                if let Some(env) = &keygroup.filter_env {
                    sfz.push_str(&format!("fileg_attack={:.3}\n", env.attack_time()));
                    sfz.push_str(&format!("fileg_decay={:.3}\n", env.decay_time()));
                    sfz.push_str(&format!("fileg_sustain={}\n", env.sustain));
                    sfz.push_str(&format!("fileg_release={:.3}\n", env.release_time()));

                    if env.depth != 0 {
                        // Convert depth (-100..100) to cents
                        let depth_cents = env.depth as f32 / 100.0 * 9600.0;
                        sfz.push_str(&format!("fileg_depth={depth_cents:.0}\n"));
                    }

                    if env.velocity_attack != 0 {
                        sfz.push_str(&format!("fileg_vel2attack={}\n", env.velocity_attack));
                    }
                    if env.on_vel_release != 0 {
                        sfz.push_str(&format!("fileg_vel2release={}\n", env.on_vel_release));
                    }
                }

                // LFOs from program level
                if let Some(lfo) = &self.lfo1 {
                    if lfo.depth > 0 {
                        sfz.push_str(&format!("lfo1_freq={:.2}\n", lfo.rate_hz()));
                        sfz.push_str(&format!("lfo1_wave={}\n", lfo.waveform_name()));
                        let depth_cents = lfo.depth_normalized() * 100.0;
                        sfz.push_str(&format!("lfo1_pitch={depth_cents:.1}\n"));

                        if lfo.delay > 0 {
                            let delay_time = (lfo.delay as f32 / 100.0) * 10.0;
                            sfz.push_str(&format!("lfo1_delay={delay_time:.2}\n"));
                        }
                    }
                }

                if let Some(lfo) = &self.lfo2 {
                    if lfo.depth > 0 {
                        sfz.push_str(&format!("lfo2_freq={:.2}\n", lfo.rate_hz()));
                        sfz.push_str(&format!("lfo2_wave={}\n", lfo.waveform_name()));
                        let depth_cents = lfo.depth_normalized() * 100.0;
                        sfz.push_str(&format!("lfo2_pitch={depth_cents:.1}\n"));

                        if lfo.delay > 0 {
                            let delay_time = (lfo.delay as f32 / 100.0) * 10.0;
                            sfz.push_str(&format!("lfo2_delay={delay_time:.2}\n"));
                        }
                    }
                }

                // Flexible modulation matrix
                self.emit_flexible_modulation(&mut sfz, keygroup);

                sfz.push('\n');
            }
        }

        sfz
    }

    /// Emit SFZ opcodes for the flexible modulation matrix.
    ///
    /// The AKP modulation system has 17 assignable routes where the source is
    /// set in the program-level `mods` chunk and the amount is stored per-keygroup
    /// (in kloc, filt, out chunks). This maps each active route to the closest
    /// SFZ opcode.
    fn emit_flexible_modulation(&self, sfz: &mut String, keygroup: &Keygroup) {
        let mods = match &self.modulation {
            Some(m) => m,
            None => return,
        };

        // --- Pitch modulation (pitch_mod_1/2 from kloc, source from mods) ---
        self.emit_pitch_mod(sfz, keygroup, mods.pitch_mod_1_source, keygroup.pitch_mod_1, "pitch_mod_1");
        self.emit_pitch_mod(sfz, keygroup, mods.pitch_mod_2_source, keygroup.pitch_mod_2, "pitch_mod_2");

        // --- Filter modulation (mod_input_1/2/3 from filt, source from mods) ---
        if let Some(filter) = &keygroup.filter {
            Self::emit_filter_mod(sfz, mods.filter_mod_1_source, filter.mod_input_1, "filter_mod_1");
            Self::emit_filter_mod(sfz, mods.filter_mod_2_source, filter.mod_input_2, "filter_mod_2");
            Self::emit_filter_mod(sfz, mods.filter_mod_3_source, filter.mod_input_3, "filter_mod_3");
        }

        // --- Amp modulation (amp_mod from kloc + amp_mod_1/2 from out) ---
        Self::emit_amp_mod(sfz, mods.amp_mod_source, keygroup.amp_mod as i32, "amp_mod");
        if let Some(output) = &self.output {
            Self::emit_amp_mod(sfz, mods.amp_mod_1_source, output.amp_mod_1 as i32, "amp_mod_1");
            Self::emit_amp_mod(sfz, mods.amp_mod_2_source, output.amp_mod_2 as i32, "amp_mod_2");
        }

        // --- Pan modulation (pan_mod_1/2/3 from out, source from mods) ---
        if let Some(output) = &self.output {
            Self::emit_pan_mod(sfz, mods.pan_mod_1_source, output.pan_mod_1 as i32, "pan_mod_1");
            Self::emit_pan_mod(sfz, mods.pan_mod_2_source, output.pan_mod_2 as i32, "pan_mod_2");
            Self::emit_pan_mod(sfz, mods.pan_mod_3_source, output.pan_mod_3 as i32, "pan_mod_3");
        }

        // --- LFO cross-modulation (SFZ2-only, emit as comments) ---
        if let Some(lfo) = &self.lfo1 {
            Self::emit_lfo_mod_comment(sfz, mods.lfo1_rate_mod_source, lfo.rate_mod as i32, "LFO1 rate");
            Self::emit_lfo_mod_comment(sfz, mods.lfo1_delay_mod_source, lfo.delay_mod as i32, "LFO1 delay");
            Self::emit_lfo_mod_comment(sfz, mods.lfo1_depth_mod_source, lfo.depth_mod as i32, "LFO1 depth");
        }
        if let Some(lfo) = &self.lfo2 {
            Self::emit_lfo_mod_comment(sfz, mods.lfo2_rate_mod_source, lfo.rate_mod as i32, "LFO2 rate");
            Self::emit_lfo_mod_comment(sfz, mods.lfo2_delay_mod_source, lfo.delay_mod as i32, "LFO2 delay");
            Self::emit_lfo_mod_comment(sfz, mods.lfo2_depth_mod_source, lfo.depth_mod as i32, "LFO2 depth");
        }
    }

    /// Emit pitch modulation for one route.
    fn emit_pitch_mod(&self, sfz: &mut String, keygroup: &Keygroup, source: u8, amount: i8, label: &str) {
        if source == 0 || amount == 0 {
            return;
        }
        let cents = amount as i32 * 100;
        let src_type = mod_source_type(source);
        match src_type {
            "lfo1" => {
                // Only emit if LFO1 isn't already emitting pitch via depth > 0
                let lfo1_already = self.lfo1.as_ref().is_some_and(|l| l.depth > 0);
                if !lfo1_already {
                    sfz.push_str(&format!("pitchlfo_depth={cents}\n"));
                }
            }
            "lfo2" => {
                sfz.push_str(&format!("lfo2_pitch={cents}\n"));
            }
            "velocity" => {
                sfz.push_str(&format!("pitch_veltrack={cents}\n"));
            }
            "keyboard" => {
                // Default SFZ behavior, skip
            }
            "aux_env" => {
                // Pitch envelope from aux envelope
                if let Some(aux) = &keygroup.aux_env {
                    let depth_cents = amount as i32 * 12; // ±100 → ±1200 cents
                    sfz.push_str(&format!("pitcheg_depth={depth_cents}\n"));
                    sfz.push_str(&format!("pitcheg_attack={:.3}\n", aux_env_rate_to_time(aux.rate_1)));
                    sfz.push_str(&format!("pitcheg_decay={:.3}\n", aux_env_rate_to_time(aux.rate_2)));
                    sfz.push_str(&format!("pitcheg_sustain={}\n", aux.level_3));
                    sfz.push_str(&format!("pitcheg_release={:.3}\n", aux_env_release(aux.rate_4)));
                }
            }
            "cc" => {
                if let Some(suffix) = mod_source_sfz_suffix(source) {
                    sfz.push_str(&format!("pitch{suffix}={cents}\n"));
                }
            }
            _ => {
                // Envelopes, deltas, unknown — emit as comment
                sfz.push_str(&format!("// {label}: source={}, amount={amount}\n", mod_source_name(source)));
            }
        }
    }

    /// Emit filter modulation for one route.
    fn emit_filter_mod(sfz: &mut String, source: u8, amount: i8, label: &str) {
        if source == 0 || amount == 0 {
            return;
        }
        // Convert amount (-100..+100) to cents (-9600..+9600)
        let cents = (amount as f32 / 100.0 * 9600.0) as i32;
        let src_type = mod_source_type(source);
        match src_type {
            "velocity" => {
                sfz.push_str(&format!("fil_veltrack={cents}\n"));
            }
            "lfo1" => {
                sfz.push_str(&format!("fillfo_depth={cents}\n"));
            }
            "lfo2" => {
                sfz.push_str(&format!("lfo2_cutoff={cents}\n"));
            }
            "keyboard" => {
                // Handled by fil_keytrack, skip
            }
            "cc" => {
                if let Some(suffix) = mod_source_sfz_suffix(source) {
                    sfz.push_str(&format!("cutoff{suffix}={cents}\n"));
                }
            }
            _ => {
                // Envelopes, deltas, unknown — emit as comment
                sfz.push_str(&format!("// {label}: source={}, amount={amount}\n", mod_source_name(source)));
            }
        }
    }

    /// Emit amplitude modulation for one route.
    fn emit_amp_mod(sfz: &mut String, source: u8, amount: i32, label: &str) {
        if source == 0 || amount == 0 {
            return;
        }
        let src_type = mod_source_type(source);
        match src_type {
            "velocity" => {
                // Already handled by amp_veltrack, skip
            }
            "lfo1" => {
                sfz.push_str(&format!("amplfo_depth={amount}\n"));
            }
            "lfo2" => {
                sfz.push_str(&format!("lfo2_volume={amount}\n"));
            }
            "cc" => {
                if let Some(suffix) = mod_source_sfz_suffix(source) {
                    sfz.push_str(&format!("volume{suffix}={amount}\n"));
                }
            }
            _ => {
                // Keyboard, envelopes, deltas — emit as comment
                sfz.push_str(&format!("// {label}: source={}, amount={amount}\n", mod_source_name(source)));
            }
        }
    }

    /// Emit pan modulation for one route.
    fn emit_pan_mod(sfz: &mut String, source: u8, amount: i32, label: &str) {
        if source == 0 || amount == 0 {
            return;
        }
        let src_type = mod_source_type(source);
        match src_type {
            "cc" => {
                if let Some(suffix) = mod_source_sfz_suffix(source) {
                    sfz.push_str(&format!("pan{suffix}={amount}\n"));
                }
            }
            "lfo1" => {
                sfz.push_str(&format!("lfo1_pan={amount}\n"));
            }
            "lfo2" => {
                sfz.push_str(&format!("lfo2_pan={amount}\n"));
            }
            _ => {
                // Velocity, keyboard, envelopes, deltas — emit as comment
                sfz.push_str(&format!("// {label}: source={}, amount={amount}\n", mod_source_name(source)));
            }
        }
    }

    /// Emit LFO cross-modulation as a comment (SFZ2-only, no clean SFZ1 mapping).
    fn emit_lfo_mod_comment(sfz: &mut String, source: u8, amount: i32, param: &str) {
        if source == 0 || amount == 0 {
            return;
        }
        sfz.push_str(&format!("// {param} mod: source={}, depth={amount}\n", mod_source_name(source)));
    }
}

/// Convert AKP aux envelope rate to attack/decay time (same curve as amp/filter).
fn aux_env_rate_to_time(v: u8) -> f32 {
    if v == 0 { 0.0 } else { (v as f32 / 100.0 * 4.0).exp() * 0.001 }
}

/// Convert AKP aux envelope rate to release time (steeper curve, 0.001s minimum).
fn aux_env_release(v: u8) -> f32 {
    if v == 0 { 0.001 } else { (v as f32 / 100.0 * 5.0).exp() * 0.001 }
}

#[cfg(test)]
mod tests {
    use crate::types::*;

    #[test]
    fn test_sfz_generation_basic() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup { low_key: 60, high_key: 72, ..Default::default() };
        keygroup.zones.push(Zone {
            sample_name: "test.wav".to_string(),
            low_vel: 1,
            high_vel: 127,
            ..Default::default()
        });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("<region>"));
        assert!(sfz.contains("sample=test.wav"));
        assert!(sfz.contains("lokey=60"));
        assert!(sfz.contains("hikey=72"));
        assert!(sfz.contains("lovel=1"));
        assert!(sfz.contains("hivel=127"));
    }

    #[test]
    fn test_sfz_filter_type_zero_is_active() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup { filter: Some(Filter { filter_type: 0, cutoff: 50, ..Default::default() }), ..Default::default() };
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("fil_type=lpf_2p"));
        assert!(sfz.contains("cutoff="));
    }

    #[test]
    fn test_sfz_resonance_from_0_12_range() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup { filter: Some(Filter { filter_type: 0, cutoff: 50, resonance: 6, ..Default::default() }), ..Default::default() };
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("resonance=20.0")); // 6/12 * 40 = 20
    }

    #[test]
    fn test_sfz_multi_zone_keygroup() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup { low_key: 36, high_key: 72, ..Default::default() };
        keygroup.zones.push(Zone { sample_name: "soft.wav".to_string(), low_vel: 0, high_vel: 63, ..Default::default() });
        keygroup.zones.push(Zone { sample_name: "loud.wav".to_string(), low_vel: 64, high_vel: 127, ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert_eq!(sfz.matches("<region>").count(), 2);
        assert!(sfz.contains("sample=soft.wav"));
        assert!(sfz.contains("sample=loud.wav"));
        assert!(sfz.contains("hivel=63"));
        assert!(sfz.contains("lovel=64"));
    }

    #[test]
    fn test_sfz_pitchbend_from_tuning() {
        let mut program = AkaiProgram { tuning: Some(ProgramTuning { pitchbend_up: 12, pitchbend_down: 12, ..Default::default() }), ..Default::default() };
        program.keygroups.push(Keygroup::default());

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("<global>\n"));
        assert!(sfz.contains("bend_up=1200"));
        assert!(sfz.contains("bend_down=-1200"));
    }

    #[test]
    fn test_sfz_amp_veltrack_from_output() {
        let mut program = AkaiProgram {
            output: Some(ProgramOutput { velocity_sensitivity: 25, ..Default::default() }),
            ..Default::default()
        };
        program.keygroups.push(Keygroup::default());

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("amp_veltrack=25")); // direct 1:1 mapping
    }

    #[test]
    fn test_sfz_amp_veltrack_omitted_at_default() {
        let mut program = AkaiProgram {
            output: Some(ProgramOutput { velocity_sensitivity: 100, ..Default::default() }),
            ..Default::default()
        };
        program.keygroups.push(Keygroup::default());

        let sfz = program.to_sfz_string();
        assert!(!sfz.contains("amp_veltrack")); // 100 = SFZ default, omitted
    }

    #[test]
    fn test_sfz_envelope_with_velocity() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup {
            amp_env: Some(Envelope {
                attack: 20, decay: 40, sustain: 80, release: 60,
                velocity_attack: -20, ..Default::default()
            }),
            ..Default::default()
        };
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("ampeg_vel2attack=-20"));
        assert!(sfz.contains("ampeg_sustain=80"));
    }

    #[test]
    fn test_sfz_filter_env_depth() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup {
            filter_env: Some(FilterEnvelope {
                attack: 5, decay: 60, sustain: 70, release: 40,
                depth: 50, ..Default::default()
            }),
            ..Default::default()
        };
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("fileg_depth=4800")); // 50/100 * 9600 = 4800
    }

    #[test]
    fn test_sfz_hardwired_modulation() {
        // Test all hardwired modulation opcodes:
        // ampeg_vel2release, fileg_vel2attack, fileg_vel2release,
        // pitch_chanaft, pitchlfo_depthcc1, pitchlfo_depthchanaft
        let mut program = AkaiProgram {
            tuning: Some(ProgramTuning {
                aftertouch: 3, // 3 semitones → 300 cents
                ..Default::default()
            }),
            lfo1: Some(Lfo {
                modwheel: 25,
                aftertouch: 10,
                ..Default::default()
            }),
            ..Default::default()
        };
        let mut keygroup = Keygroup {
            amp_env: Some(Envelope {
                attack: 20, decay: 40, sustain: 80, release: 60,
                velocity_attack: -15,
                on_vel_release: 30,
                keyscale: 5,
                ..Default::default()
            }),
            filter_env: Some(FilterEnvelope {
                attack: 10, decay: 50, sustain: 60, release: 30,
                velocity_attack: -10,
                on_vel_release: 20,
                ..Default::default()
            }),
            ..Default::default()
        };
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();

        // Global hardwired
        assert!(sfz.contains("pitch_chanaft=300"), "Missing pitch_chanaft: {sfz}");
        assert!(sfz.contains("pitchlfo_depthcc1=25"), "Missing pitchlfo_depthcc1: {sfz}");
        assert!(sfz.contains("pitchlfo_depthchanaft=10"), "Missing pitchlfo_depthchanaft: {sfz}");

        // Per-region amp env hardwired
        assert!(sfz.contains("ampeg_vel2attack=-15"), "Missing ampeg_vel2attack: {sfz}");
        assert!(sfz.contains("ampeg_vel2release=30"), "Missing ampeg_vel2release: {sfz}");
        assert!(sfz.contains("// AKP amp env keyscale=5"), "Missing keyscale comment: {sfz}");

        // Per-region filter env hardwired
        assert!(sfz.contains("fileg_vel2attack=-10"), "Missing fileg_vel2attack: {sfz}");
        assert!(sfz.contains("fileg_vel2release=20"), "Missing fileg_vel2release: {sfz}");
    }

    #[test]
    fn test_sfz_flexible_modulation_routes() {
        // Test flexible routing: LFO1→pitch, VELOCITY→filter, MODWHEEL→pan
        let mut program = AkaiProgram {
            modulation: Some(ProgramModulation {
                pitch_mod_1_source: 8,  // LFO2 → pitch
                filter_mod_1_source: 5, // VELOCITY → filter
                pan_mod_1_source: 1,    // MODWHEEL → pan
                ..Default::default()
            }),
            output: Some(ProgramOutput {
                pan_mod_1: 50,
                ..Default::default()
            }),
            ..Default::default()
        };
        let mut keygroup = Keygroup {
            pitch_mod_1: 25,  // 25 semitones → 2500 cents (for LFO2→pitch)
            filter: Some(Filter {
                mod_input_1: 75, // 75% → 7200 cents (for VELOCITY→filter)
                ..Default::default()
            }),
            ..Default::default()
        };
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();

        // LFO2 → pitch: 25 * 100 = 2500 cents
        assert!(sfz.contains("lfo2_pitch=2500"), "Missing lfo2_pitch: {sfz}");

        // VELOCITY → filter: 75/100 * 9600 = 7200 cents
        assert!(sfz.contains("fil_veltrack=7200"), "Missing fil_veltrack: {sfz}");

        // MODWHEEL → pan: amount=50
        assert!(sfz.contains("pan_oncc1=50"), "Missing pan_oncc1: {sfz}");
    }

    #[test]
    fn test_sfz_pitch_envelope_from_aux_env() {
        // When pitch_mod_2_source=11 (AUX_ENV) and aux_env exists, emit pitcheg_* opcodes
        let mut program = AkaiProgram {
            modulation: Some(ProgramModulation {
                pitch_mod_2_source: 11, // AUX_ENV
                ..Default::default()
            }),
            ..Default::default()
        };
        let mut keygroup = Keygroup {
            pitch_mod_2: 50, // ±100 → ±1200, so 50 → 600 cents
            aux_env: Some(AuxEnvelope {
                rate_1: 20,   // attack
                rate_2: 40,   // decay
                level_3: 70,  // sustain
                rate_4: 60,   // release
                ..Default::default()
            }),
            ..Default::default()
        };
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();

        // depth: 50 * 12 = 600 cents
        assert!(sfz.contains("pitcheg_depth=600"), "Missing pitcheg_depth: {sfz}");
        assert!(sfz.contains("pitcheg_attack="), "Missing pitcheg_attack: {sfz}");
        assert!(sfz.contains("pitcheg_decay="), "Missing pitcheg_decay: {sfz}");
        assert!(sfz.contains("pitcheg_sustain=70"), "Missing pitcheg_sustain: {sfz}");
        assert!(sfz.contains("pitcheg_release="), "Missing pitcheg_release: {sfz}");

        // Verify attack/release are non-zero (rate_1=20, rate_4=60 are non-zero)
        assert!(!sfz.contains("pitcheg_attack=0.000"), "pitcheg_attack should not be zero");
        assert!(!sfz.contains("pitcheg_release=0.001"), "pitcheg_release should use full curve, not minimum");
    }
}
