use crate::types::AkaiProgram;

impl AkaiProgram {
    pub fn to_sfz_string(&self) -> String {
        let mut sfz = String::new();
        sfz.push_str("// Generated by Rusty Samplers\n\n");

        // Global header from program-level data
        if let Some(tuning) = &self.tuning {
            sfz.push_str(&format!("bend_up={}\n", tuning.pitchbend_up as i32 * 100));
            sfz.push_str(&format!("bend_down=-{}\n", tuning.pitchbend_down as i32 * 100));
            sfz.push('\n');
        }

        for keygroup in &self.keygroups {
            // Each zone becomes a <region>
            let zones: Vec<_> = if keygroup.zones.is_empty() {
                // No zones — emit one region with no sample (keeps envelope/filter data visible)
                vec![None]
            } else {
                keygroup.zones.iter().map(Some).collect()
            };

            for zone in &zones {
                sfz.push_str("<region>\n");

                // Sample + velocity from zone
                if let Some(z) = zone {
                    sfz.push_str(&format!("sample={}\n", z.sample_name));
                    sfz.push_str(&format!("lokey={}\nhikey={}\n", keygroup.low_key, keygroup.high_key));
                    sfz.push_str(&format!("lovel={}\nhivel={}\n", z.low_vel, z.high_vel));

                    // Zone-level tuning (additive with keygroup)
                    let semitone = keygroup.semitone_tune as i16 + z.semitone_tune as i16;
                    let fine = keygroup.fine_tune as i16 + z.fine_tune as i16;
                    if semitone != 0 {
                        sfz.push_str(&format!("transpose={semitone}\n"));
                    }
                    if fine != 0 {
                        sfz.push_str(&format!("tune={fine}\n"));
                    }

                    // Zone pan
                    if z.pan != 0 {
                        sfz.push_str(&format!("pan={}\n", z.pan));
                    }

                    // Zone level
                    if z.level != 0 {
                        sfz.push_str(&format!("volume={}\n", z.level));
                    }

                    // Playback mode from zone
                    match z.playback {
                        0 => sfz.push_str("loop_mode=no_loop\n"),
                        1 => sfz.push_str("loop_mode=one_shot\n"),
                        2 => sfz.push_str("loop_mode=loop_continuous\n"),
                        3 => sfz.push_str("loop_mode=loop_sustain\n"),
                        _ => {} // 4=AS SAMPLE, use sample header default
                    }
                } else {
                    sfz.push_str(&format!("lokey={}\nhikey={}\n", keygroup.low_key, keygroup.high_key));
                }

                // Loudness from program output
                if let Some(output) = &self.output {
                    if output.loudness != 85 {
                        sfz.push_str(&format!("amplitude={}\n", output.loudness));
                    }
                }

                // Amp envelope
                if let Some(env) = &keygroup.amp_env {
                    sfz.push_str(&format!("ampeg_attack={:.3}\n", env.attack_time()));
                    sfz.push_str(&format!("ampeg_decay={:.3}\n", env.decay_time()));
                    sfz.push_str(&format!("ampeg_sustain={}\n", env.sustain));
                    sfz.push_str(&format!("ampeg_release={:.3}\n", env.release_time()));

                    if env.velocity_attack != 0 {
                        sfz.push_str(&format!("ampeg_vel2attack={}\n", env.velocity_attack));
                    }
                }

                // Filter
                if let Some(filter) = &keygroup.filter {
                    sfz.push_str(&format!("fil_type={}\n", filter.sfz_filter_type()));
                    sfz.push_str(&format!("cutoff={:.1}\n", filter.cutoff_hz()));
                    sfz.push_str(&format!("resonance={:.1}\n", filter.resonance_db()));

                    if filter.keyboard_track != 0 {
                        // Convert -36..+36 semitones to cents
                        sfz.push_str(&format!("fil_keytrack={}\n", filter.keyboard_track as i32 * 100));
                    }
                }

                // Filter envelope
                if let Some(env) = &keygroup.filter_env {
                    sfz.push_str(&format!("fileg_attack={:.3}\n", env.attack_time()));
                    sfz.push_str(&format!("fileg_decay={:.3}\n", env.decay_time()));
                    sfz.push_str(&format!("fileg_sustain={}\n", env.sustain));
                    sfz.push_str(&format!("fileg_release={:.3}\n", env.release_time()));

                    if env.depth != 0 {
                        // Convert depth (-100..100) to cents
                        let depth_cents = env.depth as f32 / 100.0 * 9600.0;
                        sfz.push_str(&format!("fileg_depth={depth_cents:.0}\n"));
                    }
                }

                // LFOs from program level
                if let Some(lfo) = &self.lfo1 {
                    if lfo.depth > 0 {
                        sfz.push_str(&format!("lfo1_freq={:.2}\n", lfo.rate_hz()));
                        sfz.push_str(&format!("lfo1_wave={}\n", lfo.waveform_name()));
                        let depth_cents = lfo.depth_normalized() * 100.0;
                        sfz.push_str(&format!("lfo1_pitch={depth_cents:.1}\n"));

                        if lfo.delay > 0 {
                            let delay_time = (lfo.delay as f32 / 100.0) * 10.0;
                            sfz.push_str(&format!("lfo1_delay={delay_time:.2}\n"));
                        }
                    }
                }

                if let Some(lfo) = &self.lfo2 {
                    if lfo.depth > 0 {
                        sfz.push_str(&format!("lfo2_freq={:.2}\n", lfo.rate_hz()));
                        sfz.push_str(&format!("lfo2_wave={}\n", lfo.waveform_name()));
                        let depth_cents = lfo.depth_normalized() * 100.0;
                        sfz.push_str(&format!("lfo2_pitch={depth_cents:.1}\n"));

                        if lfo.delay > 0 {
                            let delay_time = (lfo.delay as f32 / 100.0) * 10.0;
                            sfz.push_str(&format!("lfo2_delay={delay_time:.2}\n"));
                        }
                    }
                }

                sfz.push('\n');
            }
        }

        sfz
    }
}

#[cfg(test)]
mod tests {
    use crate::types::*;

    #[test]
    fn test_sfz_generation_basic() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup::default();
        keygroup.low_key = 60;
        keygroup.high_key = 72;
        keygroup.zones.push(Zone {
            sample_name: "test.wav".to_string(),
            low_vel: 1,
            high_vel: 127,
            ..Default::default()
        });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("<region>"));
        assert!(sfz.contains("sample=test.wav"));
        assert!(sfz.contains("lokey=60"));
        assert!(sfz.contains("hikey=72"));
        assert!(sfz.contains("lovel=1"));
        assert!(sfz.contains("hivel=127"));
    }

    #[test]
    fn test_sfz_filter_type_zero_is_active() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup::default();
        keygroup.filter = Some(Filter { filter_type: 0, cutoff: 50, ..Default::default() });
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("fil_type=lpf_2p"));
        assert!(sfz.contains("cutoff="));
    }

    #[test]
    fn test_sfz_resonance_from_0_12_range() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup::default();
        keygroup.filter = Some(Filter { filter_type: 0, cutoff: 50, resonance: 6, ..Default::default() });
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("resonance=20.0")); // 6/12 * 40 = 20
    }

    #[test]
    fn test_sfz_multi_zone_keygroup() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup::default();
        keygroup.low_key = 36;
        keygroup.high_key = 72;
        keygroup.zones.push(Zone { sample_name: "soft.wav".to_string(), low_vel: 0, high_vel: 63, ..Default::default() });
        keygroup.zones.push(Zone { sample_name: "loud.wav".to_string(), low_vel: 64, high_vel: 127, ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert_eq!(sfz.matches("<region>").count(), 2);
        assert!(sfz.contains("sample=soft.wav"));
        assert!(sfz.contains("sample=loud.wav"));
        assert!(sfz.contains("hivel=63"));
        assert!(sfz.contains("lovel=64"));
    }

    #[test]
    fn test_sfz_pitchbend_from_tuning() {
        let mut program = AkaiProgram::default();
        program.tuning = Some(ProgramTuning { pitchbend_up: 12, pitchbend_down: 12, ..Default::default() });
        program.keygroups.push(Keygroup::default());

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("bend_up=1200"));
        assert!(sfz.contains("bend_down=-1200"));
    }

    #[test]
    fn test_sfz_envelope_with_velocity() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup::default();
        keygroup.amp_env = Some(Envelope {
            attack: 20,
            decay: 40,
            sustain: 80,
            release: 60,
            velocity_attack: -20,
            ..Default::default()
        });
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("ampeg_vel2attack=-20"));
        assert!(sfz.contains("ampeg_sustain=80"));
    }

    #[test]
    fn test_sfz_filter_env_depth() {
        let mut program = AkaiProgram::default();
        let mut keygroup = Keygroup::default();
        keygroup.filter_env = Some(FilterEnvelope {
            attack: 5,
            decay: 60,
            sustain: 70,
            release: 40,
            depth: 50,
            ..Default::default()
        });
        keygroup.zones.push(Zone { sample_name: "t.wav".to_string(), ..Default::default() });
        program.keygroups.push(keygroup);

        let sfz = program.to_sfz_string();
        assert!(sfz.contains("fileg_depth=4800")); // 50/100 * 9600 = 4800
    }
}
