use crate::types::AkaiProgram;

impl AkaiProgram {
    pub fn to_sfz_string(&self) -> String {
        // TODO: implement with new types (Task 3)
        String::from("// Generated by Rusty Samplers\n")
    }
}
